### ISSUE TITLE
Target web for npm package

### ISSUE THREAD

**Issue by crackcomm** [lights0123/wasm-x25519#3]
I found it difficult to use this package [with bundlers](https://github.com/wasm-tool/rollup-plugin-rust/issues/7#issuecomment-666136071). Is the `web` target more suitable for npm package release? I certainly like the idea of lazy-loading and not bundling the WASM into JS as a base64-encoded string which most bundlers use anyway.

**Comment by lights0123** [comment]
What bundler are you using? With webpack, it's just:
```js
import('wasm-x25519').then(m => m.generate_keypair())
```

Edit: duh, rollup. I'll take a look at it.
